# Generated by Django 4.1.4 on 2023-01-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koppee', '0008_contactdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactdb',
            new_name='contdb',
        ),
    ]
