# Generated by Django 4.1.4 on 2023-01-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koppee', '0009_rename_contactdb_contdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contdb',
            new_name='contactdb',
        ),
    ]
