# Generated by Django 4.1.4 on 2023-01-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeweb', '0002_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactdb',
        ),
    ]
